"""add teacher profile fields

Revision ID: 1d4d6c1fa5a5
Revises: da0d2e951ef7
Create Date: 2026-03-22 22:05:42.644131

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '1d4d6c1fa5a5'
down_revision: Union[str, Sequence[str], None] = 'da0d2e951ef7'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('users', sa.Column('photo_url', sa.String(length=512), nullable=True))
    op.add_column('users', sa.Column('bio', sa.Text(), nullable=True))
    op.add_column('users', sa.Column('specialties', sa.String(length=256), nullable=True))
    op.add_column('users', sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=True))
    op.execute("UPDATE users SET created_at = now() WHERE created_at IS NULL")
    op.alter_column('users', 'created_at', nullable=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('users', 'created_at')
    op.drop_column('users', 'specialties')
    op.drop_column('users', 'bio')
    op.drop_column('users', 'photo_url')
    # ### end Alembic commands ###
