"""add_recurring_series

Revision ID: 2816b3ee1935
Revises: 987a86e04ae0
Create Date: 2026-03-18 17:41:27.596172

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision: str = '2816b3ee1935'
down_revision: Union[str, Sequence[str], None] = '987a86e04ae0'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('recurring_series',
    sa.Column('id', sa.Uuid(), nullable=False),
    sa.Column('teacher_id', sa.Uuid(), nullable=False),
    sa.Column('student_id', sa.Uuid(), nullable=True),
    sa.Column('offering_id', sa.Uuid(), nullable=False),
    sa.Column('title', sa.String(length=255), nullable=False),
    sa.Column('start_date', sa.Date(), nullable=False),
    sa.Column('interval_weeks', sa.Integer(), nullable=False),
    sa.Column('day_slots', postgresql.JSONB(astext_type=sa.Text()), nullable=False),
    sa.Column('end_date', sa.Date(), nullable=True),
    sa.Column('end_count', sa.Integer(), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.CheckConstraint('end_date IS NOT NULL OR end_count IS NOT NULL', name='ck_recurring_series_has_end_condition'),
    sa.CheckConstraint('interval_weeks >= 1', name='ck_recurring_series_interval_weeks_positive'),
    sa.ForeignKeyConstraint(['offering_id'], ['offerings.id'], ),
    sa.ForeignKeyConstraint(['student_id'], ['users.id'], ),
    sa.ForeignKeyConstraint(['teacher_id'], ['users.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.add_column('schedule_events', sa.Column('series_id', sa.Uuid(), nullable=True))
    op.create_index(op.f('ix_schedule_events_series_id'), 'schedule_events', ['series_id'], unique=False)
    op.create_foreign_key(None, 'schedule_events', 'recurring_series', ['series_id'], ['id'], ondelete='SET NULL')
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(None, 'schedule_events', type_='foreignkey')
    op.drop_index(op.f('ix_schedule_events_series_id'), table_name='schedule_events')
    op.drop_column('schedule_events', 'series_id')
    op.drop_table('recurring_series')
    # ### end Alembic commands ###
