"""add reminder_sent_at to schedule_events

Revision ID: 698e615463d4
Revises: 1d4d6c1fa5a5
Create Date: 2026-03-27 09:30:07.717752

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '698e615463d4'
down_revision: Union[str, Sequence[str], None] = '1d4d6c1fa5a5'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('schedule_events', sa.Column('reminder_sent_at', sa.DateTime(timezone=True), nullable=True))
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('schedule_events', 'reminder_sent_at')
    # ### end Alembic commands ###
