"""add_recurring_unavail_series_generalize_unavailable_blocks

Revision ID: da0d2e951ef7
Revises: 2816b3ee1935
Create Date: 2026-03-22 21:02:45.708985

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision: str = 'da0d2e951ef7'
down_revision: Union[str, Sequence[str], None] = '2816b3ee1935'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('recurring_unavail_series',
    sa.Column('id', sa.Uuid(), nullable=False),
    sa.Column('user_id', sa.Uuid(), nullable=False),
    sa.Column('note', sa.String(length=255), nullable=True),
    sa.Column('start_date', sa.Date(), nullable=False),
    sa.Column('interval_weeks', sa.Integer(), nullable=False),
    sa.Column('day_slots', postgresql.JSONB(astext_type=sa.Text()), nullable=False),
    sa.Column('end_date', sa.Date(), nullable=True),
    sa.Column('end_count', sa.Integer(), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.CheckConstraint('end_date IS NOT NULL OR end_count IS NOT NULL', name='ck_recurring_unavail_series_has_end_condition'),
    sa.CheckConstraint('interval_weeks >= 1', name='ck_recurring_unavail_series_interval_weeks_positive'),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_recurring_unavail_series_user_id'), 'recurring_unavail_series', ['user_id'], unique=False)
    # Add user_id as nullable first, backfill from teacher_id, then enforce NOT NULL
    op.add_column('unavailable_blocks', sa.Column('user_id', sa.Uuid(), nullable=True))
    op.add_column('unavailable_blocks', sa.Column('series_id', sa.Uuid(), nullable=True))
    op.execute('UPDATE unavailable_blocks SET user_id = teacher_id')
    op.alter_column('unavailable_blocks', 'user_id', nullable=False)
    op.create_index(op.f('ix_unavailable_blocks_series_id'), 'unavailable_blocks', ['series_id'], unique=False)
    op.create_index(op.f('ix_unavailable_blocks_user_id'), 'unavailable_blocks', ['user_id'], unique=False)
    op.drop_constraint(op.f('unavailable_blocks_teacher_id_fkey'), 'unavailable_blocks', type_='foreignkey')
    op.create_foreign_key('unavailable_blocks_user_id_fkey', 'unavailable_blocks', 'users', ['user_id'], ['id'])
    op.create_foreign_key('unavailable_blocks_series_id_fkey', 'unavailable_blocks', 'recurring_unavail_series', ['series_id'], ['id'], ondelete='SET NULL')
    op.drop_column('unavailable_blocks', 'teacher_id')
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('unavailable_blocks', sa.Column('teacher_id', sa.UUID(), autoincrement=False, nullable=True))
    op.execute('UPDATE unavailable_blocks SET teacher_id = user_id')
    op.alter_column('unavailable_blocks', 'teacher_id', nullable=False)
    op.drop_constraint('unavailable_blocks_series_id_fkey', 'unavailable_blocks', type_='foreignkey')
    op.drop_constraint('unavailable_blocks_user_id_fkey', 'unavailable_blocks', type_='foreignkey')
    op.create_foreign_key(op.f('unavailable_blocks_teacher_id_fkey'), 'unavailable_blocks', 'users', ['teacher_id'], ['id'])
    op.drop_index(op.f('ix_unavailable_blocks_user_id'), table_name='unavailable_blocks')
    op.drop_index(op.f('ix_unavailable_blocks_series_id'), table_name='unavailable_blocks')
    op.drop_column('unavailable_blocks', 'series_id')
    op.drop_column('unavailable_blocks', 'user_id')
    op.drop_index(op.f('ix_recurring_unavail_series_user_id'), table_name='recurring_unavail_series')
    op.drop_table('recurring_unavail_series')
    # ### end Alembic commands ###
