---
- name: Restart cloudflared
  ansible.builtin.systemd:
    name: cloudflared
    state: restarted

- name: Redeploy application
  ansible.builtin.command: >
    docker compose
    -f {{ app_dir }}/docker-compose.yml
    -f {{ app_dir }}/docker-compose.prod.yml
    up -d --build --remove-orphans
  args:
    chdir: "{{ app_dir }}"
  become_user: "{{ app_user }}"
